from enum import StrEnum


class TaskStatus(StrEnum):
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    IN_REVIEW = "IN_REVIEW"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    APPROVED = "APPROVED"


class TaskEventType(StrEnum):
    TASK_CREATED = "TASK_CREATED"
    TASK_STARTED = "TASK_STARTED"
    TASK_SUBMITTED = "TASK_SUBMITTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    TASK_APPROVED = "TASK_APPROVED"


class NotificationType(StrEnum):
    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_SUBMITTED = "TASK_SUBMITTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    TASK_APPROVED = "TASK_APPROVED"
